# -*- coding: utf-8 -*-
"""v2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TXC2mciyYtl34qI7tCfvusZ82a5ssjGA
"""

# Python equivalent of the given C++ program

# Input values
a = int(input("Enter value of a: "))
b = int(input("Enter value of b: "))
c = int(input("Enter value of c: "))
x = int(input("Enter value of x: "))

# Calculate y
y = (a * (x ** 2)) + (b * x) + c

# Output the value of y
print("Value of y:", y)
6
